// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: NameOperation.proto

#include "NameOperation.pb.h"
#include "NameOperation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* NameOperation_method_names[] = {
  "/NameOperation/SayName",
};

std::unique_ptr< NameOperation::Stub> NameOperation::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NameOperation::Stub> stub(new NameOperation::Stub(channel));
  return stub;
}

NameOperation::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayName_(NameOperation_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NameOperation::Stub::SayName(::grpc::ClientContext* context, const ::NameRequest& request, ::NameReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayName_, context, request, response);
}

void NameOperation::Stub::experimental_async::SayName(::grpc::ClientContext* context, const ::NameRequest* request, ::NameReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayName_, context, request, response, std::move(f));
}

void NameOperation::Stub::experimental_async::SayName(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NameReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayName_, context, request, response, std::move(f));
}

void NameOperation::Stub::experimental_async::SayName(::grpc::ClientContext* context, const ::NameRequest* request, ::NameReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayName_, context, request, response, reactor);
}

void NameOperation::Stub::experimental_async::SayName(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NameReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NameReply>* NameOperation::Stub::AsyncSayNameRaw(::grpc::ClientContext* context, const ::NameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NameReply>::Create(channel_.get(), cq, rpcmethod_SayName_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::NameReply>* NameOperation::Stub::PrepareAsyncSayNameRaw(::grpc::ClientContext* context, const ::NameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::NameReply>::Create(channel_.get(), cq, rpcmethod_SayName_, context, request, false);
}

NameOperation::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NameOperation_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NameOperation::Service, ::NameRequest, ::NameReply>(
          std::mem_fn(&NameOperation::Service::SayName), this)));
}

NameOperation::Service::~Service() {
}

::grpc::Status NameOperation::Service::SayName(::grpc::ServerContext* context, const ::NameRequest* request, ::NameReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


